config/routes.rb
Rails.application.routes.draw do
  resources :employments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/admin_show", to: "admin/main#index"

   # Defines the root path route ("/")
   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :pdf
end

app/models/employment.rb
class Employment < ApplicationRecord
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: %i[ show edit update destroy ]

  # GET /employments or /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1 or /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments or /employments.json
  def create
    @employment = Employment.new(employment_params)

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: "Employment was successfully created." }
        format.json { render :show, status: :created, location: @employment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1 or /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to @employment, notice: "Employment was successfully updated." }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1 or /employments/1.json
  def destroy
    @employment.destroy!

    respond_to do |format|
      format.html { redirect_to employments_path, status: :see_other, notice: "Employment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def employment_params
      params.expect(employment: [ :title, :company, :location, :start_date, :end_date, :description ])
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @qr_linkedin = QrCodeGenerator.generate("https://www.linkedin.com/in/chrisjfagg/")
    @qr_github = QrCodeGenerator.generate("https://github.com/chrisfdev00")

    @cv = Document.first
  end

  def direct_to_admin
    redirect_to "/"
  end
end

app/controllers/qr_controller.rb
class QrController < ApplicationController
  def qr_test
    qr_code = QrCodeGenerator.generate("https://google.com")
  end
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/qr_helper.rb
module QrHelper
end

app/views/admin/main/index.html.erb
<h1>ADMIN HOME</h1>

app/views/employments/_employment.html.erb
<div id="<%= dom_id employment %>">
  <p>
    <strong>Title:</strong>
    <%= employment.title %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= employment.company %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= employment.location %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= employment.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= employment.end_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= employment.description %>
  </p>

</div>

app/views/employments/_form.html.erb
<%= form_with(model: employment) do |form| %>
  <% if employment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
        <% employment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<% content_for :title, "Editing employment" %>

<h1>Editing employment</h1>

<%= render "form", employment: @employment %>

<br>

<div>
  <%= link_to "Show this employment", @employment %> |
  <%= link_to "Back to employments", employments_path %>
</div>

app/views/employments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Employments" %>

<h1>Employments</h1>

<div id="employments">
  <% @employments.each do |employment| %>
    <%= render employment %>
    <p>
      <%= link_to "Show this employment", employment %>
    </p>
  <% end %>
</div>

<%= link_to "New employment", new_employment_path %>

app/views/employments/new.html.erb
<% content_for :title, "New employment" %>

<h1>New employment</h1>

<%= render "form", employment: @employment %>

<br>

<div>
  <%= link_to "Back to employments", employments_path %>
</div>

app/views/employments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employment %>

<div>
  <%= link_to "Edit this employment", edit_employment_path(@employment) %> |
  <%= link_to "Back to employments", employments_path %>

  <%= button_to "Destroy this employment", @employment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portfolio " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/main/_qr_card.html.erb
<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title"><%= title %></h5>
    <div class="qr-code">
      <%= raw qr_code %>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div class="container vh-300 d-flex flex-column justify-content-center align-items-center mt-2">

  <div class="row justify-content-center mb-4">
    <div class="col-12">
      <div class="text-area p-5">
        <p class="font-monospace text-center mb-0 fw-bolder">
          What is this?
        </p> <br>
        <p class="font-monospace text-center mb-0">
          While this site exists in its (extreme) infancy, it will soon serve as my personal website with an admin control centre for the standard CRUD.
          This will be deployed with CI/CD configurations against a test suite in an attempt to avoid unnecessary downtime.
        </p><br>
        <p class="font-monospace text-center mb-0">
          This site will serve as a persistent sandbox for my learning experiences as a publicly documented log of the things I do and learn as a developer.
        </p><br>
        <p class="font-monospace text-center mb-0">
          This site is written in Ruby on Rails. While it is a framework I am greatly enjoying learning, it also permits returning any result as JSON by default.
        </p><br>
        <p class="font-monospace text-center mb-0">
          As such, when this site looks as it should in its Rails implementation, I will learn subdomains and treat the back-end as a headless API for other front-end frameworks.
        </p><br>
        <p class="font-monospace text-center mb-0">
          I look forward to working with you, <br>
          Chris
        </p>
      </div>
    </div>
  </div>


  <div class="row justify-content-center">
    <div class="col-auto mb-2">
      <%= render 'qr_card', title: 'LinkedIn', qr_code: @qr_linkedin %>
    </div>
    <div class="col-auto mb-2">
      <%= render 'qr_card', title: 'GitHub', qr_code: @qr_github %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <div class="row align-items-center w-100">
      <!-- Logo and Name on the Left -->
      <div class="col text-start d-flex align-items-center">
        <%= link_to root_path, class: "d-flex align-items-center text-decoration-none" do %>
          <%= image_tag("opswole.png", class: "d-inline-block me-2", height: '40', width: '40') %>
          <span class="align-middle">Christopher Fagg</span>
        <% end %>
      </div>

      <!-- Center Navigation -->
      <div class="col text-center">
        <ul class="navbar-nav d-flex flex-row justify-content-center mb-0">
          <li class="nav-item mx-3">
            <%= link_to 'Projects', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to 'Employment', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to 'About Me', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to 'Blog', root_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>

      <!-- Button on the Right -->
      <div class="col text-end">
        <%= link_to 'Admin Controls', admin_show_path, class: 'btn btn-outline-info' %>
      </div>
    </div>
  </div>
</nav>